name: CI
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  actions: read
  checks: read
  contents: read
  repository-projects: read
    

jobs:
  solidity-base:
    uses: smart-transaction/actions/.github/workflows/solidity-base.yml@main
    secrets: inherit
    with:
      disable-gas-snapshot: true # disabling gas snapshot until one is present
  static-analysis-base:
    uses: smart-transaction/actions/.github/workflows/static-analysis-base.yml@main
    with:
      disable-divide-before-multiply: true
      disable-arbitrary-send-erc20: true
  solidity-coverage:
    uses: smart-transaction/actions/.github/workflows/solidity-coverage.yml@main
    secrets: inherit
